### PR TITLE
Correction Alignment function

### PR DESCRIPTION
**Pull request by Bitico**

### CODE REVIEW

**Comment by woshilapin** [comment]
Is this a solution for the problem of the Adoxx file I've sent you?

**Comment by Bitico** [comment]
Yes. 
The last thing that remains to be done to solve the problem of file .emtl not found. I'm working on that. Gianni is working on changes to the transformation (currently in Canada at a conference) .Comunque alignment should go.

**Comment by woshilapin** [comment]
OK, I'll merge that then.  Thank you very much.  I guess I can merge #85 too then?

**Comment by Bitico** [comment]
Yes, sorry this commit try to solve #85 !

**Pull request merged**
