### PR TITLE
.emtl file not found solved

### PR DESCRIPTION
**Pull request by Bitico**

### CODE REVIEW

**Comment by woshilapin** [comment]
Hi @Bitico, thanks for the PR.  However, I'm not able to merge it.  Can you please update to the last version of the platform.

**Comment by woshilapin** [comment]
Should I close this one in favor of #98?

**Comment by Bitico** [comment]
Yes of course, sorry for the confusion!

**Comment by woshilapin** [comment]
No problem.  I'm closing it.

**Pull request closed without merging**
