### PR TITLE
[sim] Improve MON probe integration

### PR DESCRIPTION
**Pull request by tomjorquera**
This PR fixes some bugs causing the probe scores not to be correctly registered and improve the display of probe scores on the UI

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/586)

### CODE REVIEW

**Comment by acalabro** [comment]
if you update the method onMessage of the class ScoreProbeConsumer.java as described here #587 stuff will works

**Comment by tomjorquera** [comment]
@acalabro, Ok I am testing this, but the fact that the changes are distributed across several PRs makes thinks difficult.
I propose to merge this PR now, merge your PR #587, and then I will create a new PR with the proposed change on ScoreProbeConsumer. Does that sound ok?

**Comment by acalabro** [comment]
Yes. I tested it merged but locally.

**Comment by tomjorquera** [comment]
Ok let's do this

**Pull request merged**
