### PR TITLE
Emtl file bug

### PR DESCRIPTION
**Pull request by Bitico**

### CODE REVIEW

**Comment by woshilapin** [comment]
Hi @Bitico, thanks, this is getting better.  However, there is still weird modification in this PR.  Look into the tab _Files changed_ and check all the file modifications that are not related to the transformer.

**Comment by woshilapin** [comment]
The build was crashing on Travis-CI too but errors seems weird (may be related to the file modifications that shouldn't be there).  Anyway, I rerun the build in Travis just to be sure the same error happen.

**Comment by Bitico** [comment]
Probably I have some misalignement with other parts of the project not related to the transformation. I'm working on this...

**Comment by woshilapin** [comment]
Thank you :smile:

**Pull request merged**
