### PR TITLE
Proposal of interations between the CW and the OR

### PR DESCRIPTION
**Pull request by gulyx**
passing through the CP

### CODE REVIEW

**Comment by gulyx** [comment]
Jean, please consider these two statements, 

https://github.com/gulyx/learnpad/blob/interactions-between-cp-or/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java#52

https://github.com/gulyx/learnpad/blob/interactions-between-cp-or/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java#62

and also the following use of the "sim" in the class.
Not sure but it seems that this is not the right class that has to define and use any : eu.learnpad.core.impl.*XwikiBridgeInterfaceRestResource

In fact, an XwikiCoreFacadeRestResurce shuold hide a REST invocation toward the CP, like we did for the interation of the OR. Also the 
https://github.com/gulyx/learnpad/blob/interactions-between-cp-or/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java at lines 79, 110, 141 has already similar lines.

Thus shouldn’t we remove fix this aspect also?

**Comment by woshilapin** [comment]
I've investigate a bit the use of a `ClientBuilder` to generate REST calls.  It appears that this Client API exists since Jax-RS v2.0 but XWiki is still relying on Jax-RS v1.0 (yes, I think at some point, I will take a week and patch that).  However, Jersey provided a Client API (not standard though) with v1.19 (this API has been used to define the standard Client API of Jax-RS v2.0).  I tried to use it but ended up with problems with Unmarshalling (and couldn't find the solution to that).

**Comment by woshilapin** [comment]
Should I merge this one like it is?

**Comment by gulyx** [comment]
Fine with me ...
but would we deal with my last comment in a separate PR?

> Jean, please consider these two statements,
>  ... ... 
>  ... ...
>  Thus shouldn’t we remove fix this aspect also?

**Comment by woshilapin** [comment]
So yes, you're right about your comments.  I would prefer to fix that in another PR.  First reason, because it have implication on other part of the code.  Second reason, this PR is already big and it seems that it will not merge automatically so I want to focus on merging (not doing 2 things at the same time).  Please remind me to change that for another PR.

**Pull request merged**
