### PR TITLE
[ca] Content Analysis improved

### PR DESCRIPTION
**Pull request by imatesiu**
- quality criteria Presentation clarity and Completeness added
 - Grizzly embedded 
 - Now connection port is 8082
 - gully request applied: eu.learnpad.lp-cp-apis dependency added
 - Percentage of progress added in status reply

[Review on Reviewable](https://reviewable.io/reviews/learnpad/learnpad/203)

### CODE REVIEW

**Comment by woshilapin** [comment]
Reviewed 78 of 86 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java, line 39 \[r3\]](https://reviewable.io:443/reviews/learnpad/learnpad/203#-K7vAazdQ46025yML6j_:-K7vAazdQ46025yML6ja:1587551388) ([raw file](https://github.com/learnpad/learnpad/blob/e8cbe7d2a1d1b77f24861badf83b2514adbec101/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java#L39)):*
For the `@Path`,  look at the other components to see how we did it.  We usually declare the `@Path("/learnpad/ca/bridge")` and `@Path("/learnpad/ca/corefacade")` in the main interfaces (see [here](https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/BridgeInterface.java#L32) for example) and then complete the Path in the corresponding class sub-interface (like [here](https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/AskRecommendation.java#L72) for example).

---

*[lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java, line 49 \[r3\]](https://reviewable.io:443/reviews/learnpad/learnpad/203#-K7vAXCL8qSk3fJkq-ZF:-K7vAXCL8qSk3fJkq-ZG:-1326644450) ([raw file](https://github.com/learnpad/learnpad/blob/e8cbe7d2a1d1b77f24861badf83b2514adbec101/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java#L49)):*
Would be nice to remove commented code here (if ever you want it back later, git is still having it in older version of the code!).

---

*[lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java, line 66 \[r3\]](https://reviewable.io:443/reviews/learnpad/learnpad/203#-K7vCb5qm2DH_SsCUqaF:-K7vCb5qm2DH_SsCUqaG:-186046469) ([raw file](https://github.com/learnpad/learnpad/blob/e8cbe7d2a1d1b77f24861badf83b2514adbec101/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java#L66)):*
Is it some start of documentation here?  If not, as before, we should try to remove as much as possible comments which are only old code.

---

*[lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/StaticContentVerifications.java, line 43 \[r3\]](https://reviewable.io:443/reviews/learnpad/learnpad/203#-K7vDWsO2O7nFpR1WkPQ:-K7vDWsPBJ0ufeKKsgnF:273673207) ([raw file](https://github.com/learnpad/learnpad/blob/e8cbe7d2a1d1b77f24861badf83b2514adbec101/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/StaticContentVerifications.java#L43)):*
As expressed in another comment, if you put the `@Path("/learnpad/ca/bridge")` in the main interface, you'll avoid to repeat it here (and also, it'll be more easy to change it later).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/learnpad/learnpad/203)*

**Comment by woshilapin** [comment]
Nice and big work.  I've made a few remarks, mainly on the `lp-core-platform` part.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/learnpad/learnpad/203#-:-K7vE8eWkrIIDOvZghh1:1849402731)*

**Comment by imatesiu** [comment]
@woshilapin thanks for comments. 
I close this PR and re-request when i apply the comments, ok?
thanks

**Comment by woshilapin** [comment]
No, no, you don't have to close the PR.  You just have to add the modification on a new commit and push to the same branch of your own repository `ISTI-FMT-LearnPAd:contentanalysis_grizzly`.  Then the PR will automatically take these new commits into account.

**Comment by woshilapin** [comment]
I agree, this feature from PR on Github is not well documented and obvious :smile:

**Comment by imatesiu** [comment]
ok perfect! thanks @woshilapin

**Comment by woshilapin** [comment]
Oh, and tell me when you're finished because the bad part of Github is that it doesn't send me an email when new commits arrive.  Just put a comment here (for that it's sending email!). Thanks

PS: You can have multiple `@Path()` in the same class: you can have one before the name of the class (like you did before), then on top of that, one more specific for each function.
For example, you can do like the following:
```
@Path("/validatecollaborativecontent")
public interface ColloborativeContentVerifications {
	@Path("/")
	@POST
	String putValidateCollaborativeContent(@FormParam("collaborativecontent") CollaborativeContentAnalysis contentFile)
 				throws LpRestException;

	@Path("/{idAnnotatedCollaborativeContentAnalysis:.*}/status")
	@GET
 	String getStatusCollaborativeContentVerifications(@PathParam("idAnnotatedCollaborativeContentAnalysis") String contentID)
 			throws LpRestException;
}
```

Like always, if copy/paste is a good friend but if you can factorize code, it's better for maintenance :smile:

**Comment by imatesiu** [comment]
@woshilapin Now i have done, i think ;)

**Comment by woshilapin** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/learnpad/learnpad/203)*

**Comment by woshilapin** [comment]
OK, perfect, I'm waiting for Travis to check the build (but it should be OK) and then I merge it.  Thanks for the work.

**Comment by imatesiu** [comment]
@woshilapin my thanks for your support!

**Pull request merged**
