### PR TITLE
POST request queryparam into Formparam changed

### PR DESCRIPTION
**Pull request by imatesiu**
*POST request queryparam into Formparam changed 
*bugfix toString() Content class
*delete PUT request

### CODE REVIEW

**Comment by woshilapin** [comment]
You are changing the API (remove a function and change from Query to Form parameter), could you explain a bit why and give some details?  It would be nice also if @gulyx could review that too.

**Comment by imatesiu** [comment]
I have changed the query param into form param to send the xml file from platform to component through http request body.
I made a mistake on the first commit, sorry about that.

**Comment by woshilapin** [comment]
From what I understand, you don't want a  `@FormParam` but a whole Java class.  You can describe a Java class to be easily transformed into a XML.  If you do so, then you can give this Java class as an argument of your function (last argument) and it will be automatically serialize/deserialize into/from XML.

For example, see [Feedbacks class](https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/Feedbacks.java) and how it's annotated with XML.  And then, I use this class in [getFeedbacks API](https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/GetFeedbacks.java#L44).  But I could also create a `PUT` method that would take `Feedbacks` as an input like the following.

```java
@Path("/{modelsetid}/feedbacks")
@PUT
void getFeedbacks(@PathParam("modelsetid") String modelSetId, Feedbacks feedbacks)
			throws LpRestException;
```

**Comment by imatesiu** [comment]
ok Jean, thanks for your suggestion. I close this pull request, I delete formparam and  I open
new  pull request ok?

**Comment by woshilapin** [comment]
You have 2 solutions, either add other commits on this same branch (and they will appear on this Pull Request) or close this Pull Request and open a new one.  Both are fine to me (maybe second option will be more pertinent in this case, indeed).

**Pull request closed without merging**
