### PR TITLE
lp-content-analysis UI added

### PR DESCRIPTION
**Pull request by imatesiu**
*the method returning the URL implementated
*scripts build/start/stop improved

@gulyx this is new PR.

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/442)

### CODE REVIEW

**Comment by gulyx** [comment]
@imatesiu ok better. I am looking at it.

**Comment by gulyx** [comment]
@imatesiu I am not sure if the newline at the end of the file is needed both [here](https://github.com/LearnPAd/learnpad/pull/442/files#diff-8c01d7935cdb1ec9babc46e7a3d8e479R9) in the other bash files. Probably yes it is.

Also, I am not sure that [this implementation](https://github.com/LearnPAd/learnpad/pull/442/files#diff-504120f644162ced275589dc092ce4d1R217) is compliant with the various deploy we may experience (without rebuilding). Could we rely on an external conf file, or something similar?

**Comment by imatesiu** [comment]
`config.properties` file added to insert ip and port of the UI component. 

Ok ? @gulyx

**Comment by imatesiu** [comment]
@gulyx  Travis fails because  repository.apache.org is temporarily unavailable

**Comment by gulyx** [comment]
@imatesiu I guess I can merge it, right?

**Comment by imatesiu** [comment]
@gulyx yes merge! ;)

**Pull request merged**
