### PR TITLE
First proposal for the DocPages (in English)

### PR DESCRIPTION
**Pull request by gulyx**
@cjdelisle please help me to revise it. On my local it compiles and looks working, but I would l like that 
you check (and maybe accept) this PR. Let me know.

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/450)

### CODE REVIEW

**Comment by cjdelisle** [comment]
Hmm I'd rather this be 1 page than multiple and also the use of a Translations page is not required, simply set your wiki to multi-lingual ("LOCALIZATION" section of Administration) and add it to SUPPORTED LANGUAGES (comma separated) then return to the page and edit it and then click "Translate this page in: it" on the righthand panel.

**Comment by gulyx** [comment]
@cjdelisle about translations (i.e. https://github.com/gulyx/learnpad/blob/c345ac4214992e24f1775a901ec0dd7b77e96b27/lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml) I am trying to follow the approach originally set by @woshilapin.

**Comment by cjdelisle** [comment]
For UI components, yes, you need to use translations like that. For entire pages (especially help pages) it's better to simply translate the page.

**Comment by gulyx** [comment]
ok @cjdelisle I will try to modify the contribution to this PR in that sense.
Btw, I was not able to understand how to enable by default the multi-language support in the wiki build form the building system of learnpad. Any suggestion/idea?

**Comment by cjdelisle** [comment]
ahhh indeed, try exporting your XWiki.XWikiPreferences and then add it to the repository, that should be the best way.

**Comment by cjdelisle** [comment]
+1

**Comment by gulyx** [comment]
@cjdelisle wait a bit before merging. I am still writing some code i would like to add this PR

**Comment by gulyx** [comment]
@cjdelisle please revise these last commits, and in case i will let u to merge the PR

**Comment by cjdelisle** [comment]
Structure looks good, but do you really want to include the documents without writing *any* content ?  What is your plan for this ?

**Comment by gulyx** [comment]
@cjdelisle my plan is that somebody write the content (especially the italian part), but not now ... and hopefully not only me.

I would like to see first if this structure conforms with the expectations of everybody, and then look for contents.

In conclusion, if for u the PR is fine accept it so also the others can see the DocsPanel

**Pull request merged**
