### PR TITLE
[ca] Contentanalysis bug fix 

### PR DESCRIPTION
**Pull request by imatesiu**
* Juridical Jargon bug fix
* Correctness analysis bug fix

[Review on Reviewable](https://reviewable.io/reviews/learnpad/learnpad/177)

### CODE REVIEW

**Comment by imatesiu** [comment]
@woshilapin Travis say :
* /home/travis/build/LearnPAd/learnpad/build-system/utils.sh: line 19: syntax error near unexpected token `fi'

**Comment by woshilapin** [comment]
Hi @imatesiu,

Yes, I saw that but you probably synchronized almost exactly at the wrong time (no luck).  Because this bug stayed less than 30mn on the repo.  Anyway, update you PR with the last version of the repo and it should be fine.  Sorry for the inconvenience.

**Comment by imatesiu** [comment]
thanks @woshilapin, but the last version of the repo contains same problem. 
https://travis-ci.org/LearnPAd/learnpad/builds
Maybe you  did not  pushed fix bug in repository?

**Comment by woshilapin** [comment]
I did fix it... but push it only to my repository (oups).  OK, you have nothing to do now, I'll merge it, thanks and sorry for noise.

**Pull request merged**
