### PR TITLE
Fixed Undesidered "PrintStackTrace" With Exception Chaining in CP

### PR DESCRIPTION
**Pull request by gulyx**
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/415)

### CODE REVIEW

**Comment by woshilapin** [comment]
Hi @gulyx, nice idea.  Only 2 things:
* please remove the lines instead of commenting them
* I've done a big reformatting of all files (indentation and remove unused import), could you configure your Eclipse to make it happen too?

**Comment by woshilapin** [comment]
Still not the good indentation. Please use `<CTRL>+<SHIFT>+F` to let Eclipse format the file. The configuration I used is `Eclipse [built-in]` (in `Window -> Preferences`, go into `Java -> Code Style -> Formatter` and choose `Eclipse [ built-in]`.

Also, you can make it automatic whenever you save the file (in `Window -> Preferences`, go into `Java -> Editor -> Save Actions` then click on `Format Source Code` and `Organize imports`).

**Comment by gulyx** [comment]
ah yes ... i forgot

**Comment by woshilapin** [comment]
Thanks

**Pull request merged**
