### PR TITLE
Panel space name and maven edit

### PR DESCRIPTION
**Pull request by danielegagliardi6**
Updates on Panels creation and recognition between panels from other spaces.
Name of the space have been added to the name of the panel
Maven Test inserted

### CODE REVIEW

**Comment by woshilapin** [comment]
You shouldn't modify what is in the root directory.  Do not touch `.gitignore` and do not create a `pom.xml`.  So I cannot accept this pull request as long as these files are created/modified.  You may create them for your own development environment but you should not publish them.

**Comment by danielegagliardi6** [comment]
The .gitignore file was modified directly by the Eclipse workspace and the pom.xml file was already there into another folder and I just inserted these rows as a test. There are other changes for the panels recognition that are important because otherwise the software will overwrite existing ones.
Is it possible to push only that changes?

**Comment by woshilapin** [comment]
Yes, sometimes, Eclipse or other tools may add, modify or delete files.  However, you should manage carefully what file you commit and what file you don't touch at git level.  Somewhere, you should have seen that `.gitignore` has been modified (with `git status` for example).  Since this file should not be modified, when you're trying to make your git commit, you must make `git add` for only the files that you consciously modified.

Another way of saying, it's not a problem that you have these files on your computer.  However, it does not mean that you need to commit them on the official git repository.

Now, what you can do to solve the problem is make another commit where:
- you remove the added line (about `target/`) in the `.gitignore`
- `git rm --cached pom.xml` to remove the `pom.xml` (but `--cached` will not physically remove the file from your hard drive)
Then you can push this new commit and everything should be OK I think.

**Comment by woshilapin** [comment]
Most of the parts of this Pull Request has been merged into `lp-collaborative-workspace/lp-collaborative-workspace-bridge/lp-collaborative-workspace-bridge-importer/lp-collaborative-workspace-bridge-importer-adoxx/` (I've changed a bit the hierarchy of the Collaborative Workspace's component).  I've done some modifications n your Pull Request to avoid to crash the build (look at the `pom.xml`).

**Pull request closed without merging**
