### PR TITLE
[ca] Contentanalysis

### PR DESCRIPTION
**Pull request by imatesiu**
Technical Jargon added in Simplicity

[Review on Reviewable](https://reviewable.io/reviews/learnpad/learnpad/179)

### CODE REVIEW

**Comment by imatesiu** [comment]
Hi @woshilapin The CA component is packaged as a WAR to be deployed on an Application Server like Tomcat. The port 8080 is defined in server.xml of Tomcat, so if you wish to change it you should modify server.xml on your side, I guess. To define the port in the component I can change it by adding a component-embeddable WebServer, like Jetty. Tell me which option do you prefer.

**Comment by woshilapin** [comment]
Ah, then I may be able to deploy it on the already existing Jetty I use for XWiki.  But since it's not the same component, I'm not sure what is the best way to do it automatically.  Maybe I could use that WAR as a dependency on my build.  But there is a lot of fog for me here: I never used WAR in dependencies of Maven, the XWiki packager is building with Jetty but I'm not mastering this packager tool so maybe it's not possible (need to ask).  If I have time, I'll investigate that.  In any case, we will discuss that on the meeting of January. Thanks

**Comment by gulyx** [comment]
@woshilapin @imatesiu if it is possible I would avoid to create any specific dependency that is only justified by "implementation details" related to a couple of components ... In fact it would be nice if the components (developed with a independent technology from xwiki) can be actually deployed and used as separate modules. This will increase the modularity of Learn PAd, but also the modularity of the components themselves. 

However, I know that this may require an extra effort ... especially in the development of the component, so please you both feel free to propose the solution that is more convenient for everybody.

Please let me know.

**Comment by woshilapin** [comment]
Note that this dependency already exists for OR and CW.  Just to remind you, we have CP, CW and OR as independent component.  Then you have `lp-platform` that uses all of them as dependencies to build a WAR.  I was talking about putting `lp-content-analysis` WAR as a dependency of this `lp-platform` build which is just a convenient aggregator's build, not really a component.

**Comment by gulyx** [comment]
@woshilapin as far as i can remember the OR is a component that is supposed to be developed as XWiki Component ... thus I would say that is normal. Not sure if this is the case for the CA. @imatesiu can you confirm? Where in the component is implemented the Bridge? Where the CoreFacade from the CP is used?

**Comment by imatesiu** [comment]
@gulyx CA is an independent component. The component implements the Bridge only in eu.learnpad.ca.rest.impl.
@woshilapin  i prepared quickly the CA component with embedded Jetty via Maven (https://goo.gl/PhsWKs), and Grizzly via Main (https://goo.gl/bgKiBq).
Now or on the meeting of January you will tell me which option do you prefer. Thanks

**Comment by gulyx** [comment]
@imatesiu fine, and also that was what i was expecting.
Some suggestion considering your code : 
 * it is a bit odd that you are redefing APIs here : https://github.com/LearnPAd/learnpad/tree/master/lp-content-analysis/src/main/java/eu/learnpad/ca/rest . I would suggest to remove it and include a explicit dependency with the lp-cp-apis module.
* about the REST impl in https://github.com/LearnPAd/learnpad/tree/master/lp-content-analysis/src/main/java/eu/learnpad/ca/rest/impl , I would suggests to you refactor this implementation by directly providing an explicit implementation of the interface Bridge defined here : https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/Bridge.java . This way any possible future modification on the API will be automatically reflected also in the code of the component. 
* A similar approach is recommended also for the invocation of the rest API exposed by the CP, so encapsulate the invocations into a class that implements eu.learnpad.ca.CoreFacade

Would it be possible? Please let me know.

**Comment by gulyx** [comment]
@imatesiu, any feedback about this conversation?
Please let me know.

**Comment by imatesiu** [comment]
@gulyx
yes it is possible. What you say is correct, but I don't agree. 
In this way the component is not more indipendent from the LearPAd platform.
Indeed, if I want to compile it without the LearnPAd repository, I will not be able to compile it. 

Moreover, in any case, possibile future modification on the REST API to upgrade the interface, 
 should be implemented in lp-cp-apis and into CA rest.impl. 

My suggestion is to use jitpack to publish lp-cp-apis source code (https://jitpack.io)

However, if you prefer to go in the direction that you suggested, I will apply your recommendation in January
 when we have decided if we prefer to integrate jetty or grizzly in the CA component.

**Comment by gulyx** [comment]
@imatesiu i try to better explain my positions, and again
I am not forcing you to take any specific direction. I am only 
trying to discuss alternative solutions that may better support
the maintenance of the platform. 

The components are supposed to be independent, in the 
sense that there is no imposition on how to develop the component ...
but of course we expect it exports the API defined in lp-cp-api.
The implementation of these API are delegated to the Bridge, which it is actually
implementing the "dependancy" between the component and the rest of 
the architecture. As an example, kind of such a dependency is expressed
by the Path annotation on the API (e.g. "/learnpad/ca/... ....").
Thus for sure the Bridge is supposed to be "somehow dependent" on lp-cp-api.

The suggestion is to develop the behaviour of the component independently
as you wish; but also to implement a BridgeImpl which inherits from lp-cp-api
where each operation properly interact with the actual component. Among the others,
one of the benefit of this organization is that it will grant that possible future
modifications on the API will be automatically reflected also in the code of the component. 

About the compilation, if someone download the the whole lp-ca component from 
the Learn PAd repo, I do not consider a shame if the API of the CP are required.
But thinks may be organized in order to support the compilation only for a part of the
lp-ca component : for example the single ca part. 

This, how to organize the project? Again, feel free to decide any implementation for the solution, and possibly @woshilapin may have some suggestions in this sense.
However,  a possibility can be the one followed by @damianofalcioni. Please see here : 
https://github.com/LearnPAd/learnpad/tree/master/lp-model-verification
where : 
 * the sub-project lp-verification-component implements the Bridge and the interactions with the CP
 * the other sub-projects are implementing the actual component as independent from Learn PAd

Perhaps, you would like enhance his solution, in the sense that the different mvn projects have the 
"right" dependencies among the Learn PAd, and the CA specific parts ... but this is really up to you.

I hope this clarify.
Please let me know if it make any sense or not.

**Comment by imatesiu** [comment]
@gulyx What you say is correct and clear. I understood your suggestion also in first message.
  I will apply your recommendation in January
when we have decided if we prefer to integrate jetty or grizzly in the CA component.

**Pull request merged**
