### PR TITLE
[mon] updates for integration and rules generation

### PR DESCRIPTION
**Pull request by acalabro**
Update to the rules generation, now will be instanciated a rule for each
user for each path, (users*path) rules. The rules generated are
correctly loaded within the Complex Event Processor so they are
syntactical correct. Test for the semantic aspect are needed

@tomjorquera  please note that the class file GlimpseBaseEventBPMN 
https://github.com/acalabro/learnpad/blob/master/lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/event/GlimpseBaseEventBPMN.java

has been modified adding some methods needed by CEP for grabbing data from the events.
 This should not impact on your side, but.. take it in account :)

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/528)

### CODE REVIEW

**Comment by acalabro** [comment]
@tomjorquera 
I think the last change impact on simulator.

I just removed a duplicated class within the monitor.
The class was eu.learnpad.simulator.mon.coverage.ScoreType
you should just update your references now with the version that is on the API

**Comment by tomjorquera** [comment]
As I just told @acalabro offchannel. This error is probably due to the fact that this PR is made against an older version of the reference master branch.
Rebasing the changes should make the errors in the SImulator clear.

**Comment by gulyx** [comment]
@tomjorquera are you going to deal with this, right?

**Comment by tomjorquera** [comment]
@gulyx : yes it seems fine now, let's merge it

**Pull request merged**
