### PR TITLE
[ca] lp-content-analysis UI added

### PR DESCRIPTION
**Pull request by imatesiu**
* the method returning the URL implementated
* scripts build/start/stop improved

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/441)

### CODE REVIEW

**Comment by gulyx** [comment]
sorry @imatesiu, i cannot see any change in the files from this PR. Am I missing something?

**Comment by imatesiu** [comment]
@gulyx i don't know why github doesn't show my changes. try pressing the individual commits.

**Comment by gulyx** [comment]
@cjdelisle @tomjorquera any idea/hint?

**Comment by gulyx** [comment]
@imatesiu from  (L217)[https://github.com/ISTI-FMT-LearnPAd/learnpad/blob/d9bb3302a94e95adb178bef4965a766196c2ea7d/lp-content-analysis/src/main/java/eu/learnpad/ca/impl/BridgeImpl.java#L217] and [L441](https://github.com/ISTI-FMT-LearnPAd/learnpad/blob/d9bb3302a94e95adb178bef4965a766196c2ea7d/lp-content-analysis/src/main/java/eu/learnpad/ca/impl/BridgeImpl.java#L411) I understand this PR is not providing yet the implementation of
the method computing the URL for the LP-CA-UI. Is that correct?

**Comment by imatesiu** [comment]
ok @gulyx  I close this PR and I Open new  correct PR.

**Pull request closed without merging**
