### PR TITLE
D5 dashboard and analysis

### PR DESCRIPTION
**Pull request by semmeneg**
Sim score API implementation, updated testcases and email addresses for validation.

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/523)

### CODE REVIEW

**Comment by gulyx** [comment]
@semmeneg i tested this version wrt to the latest version of the model released by barbara and the users defined [here](https://github.com/LearnPAd/learnpad/blob/master/lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUsers/UsersListY3Demo.xml#L42), but still no recommendations. Could you please check and let me know?

**Comment by gulyx** [comment]
Also @semmeneg are you sure at this point we would like to change this rest API ?
https://github.com/LearnPAd/learnpad/pull/523/commits/7a88cad8d18fd99c7ec3ac925b4fe17e77afc63e#diff-61ad1f7a408759062bc742dcde8ad67dL95
Is that intentional or rather it is a regression?
Please verify.

**Comment by gulyx** [comment]
@semmeneg,
again me. I noticed [here](https://github.com/LearnPAd/learnpad/pull/523/files#diff-fb1e2b85a25c039313fd727d2c1d6bf0R3) you are redefining again the type of simulation scores supported
by the platform. Since we are at the API level, wouldn't be better to reuse the definition in the [SIM]( https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/ScoreType.java)? I also see advantages in your choice since the coupling of the two components is lower. What do you suggest? What's about you @acalabro ?

**Comment by acalabro** [comment]
@semmeneg @gulyx 
Events that will be notificated through the sim by mon will follow this format
https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ScoreUpdateEvent.java
ScoreUpdateEvent 
and within this object there are:
ScoreType scoreUpdateName 
Float scoreUpdateValue

**Pull request merged**
