### PR TITLE
[sim] Update score desc in ui

### PR DESCRIPTION
**Pull request by tomjorquera**
Change the scores desc in UI according to proposal in #577 

Minor fixes

### CODE REVIEW

**Comment by acalabro** [comment]
I suggest this modification before merge

>                     if(userscore.hasOwnProperty('ABSOLUTE_SESSION_SCORE')) {
                        result += '<tr><td><i>Top score reachable for this session</i></td><td><i>' + userscore.ABSOLUTE_SESSION_SCORE + '</i></td></tr>';
                    }
                    if(userscore.hasOwnProperty('BP_COVERAGE')) {
                        result += '<tr><td><i>Your percentage of modelset discovered</i></td><td><i>' + userscore.BP_COVERAGE + '%</i></td></tr>';
                    }
                    if(userscore.hasOwnProperty('BP_SCORE')) {
                        result += '<tr><td><i>Your best scores for this modelset</i></td><td><i>' + userscore.BP_SCORE + '</i></td></tr>';
                    }
                    if(userscore.hasOwnProperty('RELATIVE_BP_SCORE')) {
                        result += '<tr><td><i>Best score reachable for this modelset</i></td><td><i>' + userscore.RELATIVE_BP_SCORE + '</i></td></tr>';
                    }
                    if(userscore.hasOwnProperty('GLOBAL_SCORE')) {
                        result += '<tr><td><i>Max scores obtained on all explored modelsets</i></td><td><i>' + userscore.GLOBAL_SCORE + '</i></td></tr>';
                    }
                    if(userscore.hasOwnProperty('ABSOLUTE_GLOBAL_SCORE')) {
                        result += '<tr><td><i>Best score reachable for all explored modelsets</i></td><td><i>' + userscore.ABSOLUTE_GLOBAL_SCORE + '</i></td></tr>';
                    }

**Comment by gulyx** [comment]
@acalabro sorry which file?

**Comment by gulyx** [comment]
@acalabro ... ups! just one file for the moment. sorry!

**Comment by acalabro** [comment]
https://github.com/tomjorquera/learnpad/blob/03090d824673203e4fc291cd2dc7394ba75f0433/lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js

**Comment by gulyx** [comment]
@tomjorquera what's about this PR?

**Comment by tomjorquera** [comment]
let's merge this

**Pull request merged**
