### PR TITLE
[mon] Add monitoring component to the platform

### PR DESCRIPTION
**Pull request by tomjorquera**
Add the monitoring component code base to the platform (with some minor patching).
Add it to the build system component list.
Update gitignore with monitoring needs.

@acalabro should review this before the PR is merged.

As a side note, while this component is separate from the simulation component. The plan is still to keep a unified API for now.

### CODE REVIEW

**Comment by gulyx** [comment]
@tomjorquera @acalabro, as I already commented in #106, I do not think that we should introduce a new component. Again, I am totally fine with separating "sim" from "mon" in two different packages,
but from the point of view of the CP, they should still appear as a single component.

In other words, partitioning the package "eu.learnpad.simulator" into : "eu.learnpad.simulator.sim"
and "eu.learnpad.simulator.mon" it is fine, but they should work under commons BridgeInterface and
CoreFacade.

In this sense I assume we cannot merge this PR!

**Comment by tomjorquera** [comment]
Sorry @gulyx but maybe I misunderstood your comment on PR #106. I initially believe that your concern was having 2 separate APIs instead of an unified one.

This PR only proposes to separate the implementations of the simulator and monitoring components, but they should still work over a unified API. On a side note, in the current design the monitoring part does not exposes any API, so from the point of view of the CP this separation is trully completely transparent. But even if it was not the case, the could still function other a common BridgeInterface (the implementation of the Bridge assuring the dispatch between the REST APIs of the two components, but this dispatch will be inevitable whatever the design as the simulator and monitoring are fundamentally two separate projects).

Using a (somewhat hazardous) metaphor, the functionalities are still logically unified (by a common API) and only "physically" separated.

I proposed this PR as @acalabro created the required build/start/stop scripts to make the monitoring into a full-fledged component. Since these efforts have already been undertaken, I don't think it is useful to unravel all of this to force this separate project into a subpart of the simulator (as they are truly two separate projects, with separate pom, dependencies and so on).

I really think the current state of this PR is sound. From my understanding, the integration is quite clean and still in line with that you requested in PR #106 reguarding the API. Do you still feel we should still take the additional effort of merging the two projects in a single one ?

**Comment by gulyx** [comment]
@tomjorquera, even thought I was expecting something different, at the end we agreed that lp-monitoring is not a component of learnpad, but rather it is a sub component of the simulation environment. This means that lp-monitoring does not offer any functionality to the platform di-per-se, and its "scope" is defined within the lp-simulation umbrella.

As we always said, components can be structured in a very complex and articulated way, but 
all these sub-layering should not appear form top level view

In this sense I still believe that the monitoring should be "hidden" by the simulator, even with respect to the build and the dependencies, otherwise the problem of keeping this two different sources for the same functionality aligned, it will simply be shifted at the higher level of the architecture. I see this as risky and time consuming wrt the overall integration.

Also, as far I understood both lp-simulaton and lp-monitoring relies on the same technology, and  @acalabro already brought the project in mvn structure. Thus, the integration of the build scripts from lp-monitoring with the existing ones (in lp-simulator) shouldn't be to much complex. As I suggested yesterday to @acalabro, he may PR such a new version on your side, and then open again a PR.

Please let me know.

**Comment by tomjorquera** [comment]
@gulyx, based on your last message, I have to admit I am now actually unsure of what you have in mind regarding the integration of the simulator and monitoring components.

From your previous message, I was believing you were suggesting to merge the two project into a single java project, a challenging but ultimately "clean" design. But @acalabro's PR is clearly something different.

Here is the PR @acalabro sent me (he mistakenly did it against the old learnpad-simulator project instead of the current learnpad one, but this is incidental to the topic):
https://github.com/tomjorquera/learnpad-simulator/pull/1/

Is it what you had in mind? I think it is more of a misunderstanding, because this does not solve any of your concerns, while bringing a lot of additional pain to everyone.

Technically, it is basically exactly the same things than this PR (minus the small bugs I corrected), except with the files in another physical location.
Also @acalabro's PR is actually incomplete, since it does not actually integrate the monitoring component anywhere. Looking at it it seems to me that it needs to add its own components system (the "cleaner" way in this state would probably be to basically copy-paste the build/launch scripts from the main platform).

Could you confirm whether or not @acalabro's PR corresponds to what you intended (disregarding that it is incomplete in some regards)?

On a side note, as I told @acalabro, I *strongly* discourage anyone to base his work on my personal fork of the project. Not that I am very possessive mind you, but because I use my fork of the repo as my own instable "sandbox" to clean-up my code before adding my contributions to the main repo, along with my "in-progress" code backup.
I do a lot of messy, experimental work in there, which often ends in aggressive rebases, resets and/or pushs -f. If he tries to base his contributions on this repo, things will break in an ugly way sooner or later.
He should use the canonical learnpad/learnpad repo instead, which we agreed should always be in a "pristine" state, and make his PRs here as the other contributors do.

**Comment by woshilapin** [comment]
Hi @gulyx, @tomjorquera and @acalabro, shoud I merge this PR or wait for another one?

**Comment by gulyx** [comment]
please wait ... i need to answer @tomjorquera  :smile:

**Comment by gulyx** [comment]
@woshilapin I just talked with @tomjorquera via Skype. We clarified the issues and planned a solution. @acalabro, I am not  sure if @tomjorquera needs any supports from you; probably yes. 

@tomjorquera, would  you commit the changes on this PR, right?

**Comment by acalabro** [comment]
ok

**Comment by tomjorquera** [comment]
@woshilapin please do not merge this yet even if @gulyx and @acalabro say it is ok.

I need to take care of some work in progress on my side that obviously get *very* broken as I just moved *a lot* of files.

If this PR seems fine to everyone, I will first integrate some of my pending changes, and I will then rebase the PR on top of those before we merge it.

**Comment by woshilapin** [comment]
OK, I'm waiting for your GO.

**Comment by tomjorquera** [comment]
Ok, everything is now clean on my side. The PR can be merged if @gulyx and @acalabro think it is adequate.

**Comment by gulyx** [comment]
it looks fine with me

**Comment by woshilapin** [comment]
OK, I'll merge it.

**Pull request merged**
