### PR TITLE
[ca] lp-content-analysis User Interface

### PR DESCRIPTION
**Pull request by imatesiu**
* Source code of the User Interface of the lp-content-analysis

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/428)

### CODE REVIEW

**Comment by gulyx** [comment]
@imatesiu, is the whole tomcat included in this PR? If so, do we actually need it? can't we simply expose the lp-ca-ui from jetty?

**Comment by imatesiu** [comment]
@gulyx the fast way to use jetty to run component is in `lp-content-analysis/lp-ca-ui/scripts/start` using command `java -jar jetty-runner.jar --port 9090 *.war`

**Comment by gulyx** [comment]
@imatesiu so for the best I can understand the lp-ca-ui was wrote for tomcat and in the way u configured the scripts it results build as a war which is later executed on jetty ... so there is not tomcat instance/dependency around, right?

In this case, which is the pourpose of both [lp-content-analysis/lp-ca-ui/build_tomcat](https://github.com/ISTI-FMT-LearnPAd/learnpad/blob/contentanalysis_UI/lp-content-analysis/lp-ca-ui/build_tomcat) and [lp-content-analysis/lp-ca-ui/build_tomcat.bat](https://github.com/ISTI-FMT-LearnPAd/learnpad/blob/contentanalysis_UI/lp-content-analysis/lp-ca-ui/build_tomcat.bat) in this commit?

Also, I am a bit confused about the description in the file : [lp-content-analysis/lp-ca-ui/README.md](https://github.com/ISTI-FMT-LearnPAd/learnpad/blob/contentanalysis_UI/lp-content-analysis/lp-ca-ui/README.md). Is this description updated and does it actually refer to the lp-ca-ui?

**Comment by imatesiu** [comment]
> @imatesiu so for the best I can understand the lp-ca-ui was wrote for tomcat and in the way u configured the scripts it results build as a war which is later executed on jetty ... so there is not tomcat instance/dependency around, right?

yes, is correct.

>In this case, which is the pourpose of both lp-content-analysis/lp-ca-ui/build_tomcat and lp-content-analysis/lp-ca-ui/build_tomcat.bat in this commit?

these scripts are old I removed they


>Also, I am a bit confused about the description in the file : lp-content-analysis/lp-ca-ui/README.md. Is this description updated and does it actually refer to the lp-ca-ui?

 the description is not correct, now I removed the description

**Comment by gulyx** [comment]
thanks @imatesiu, but sorry for this last request from my side :-P 

- can u add again a Readme.md documenting the lp-ca-ui and in particular the port it is using?
- the port 9090 appears to be "common", so maybe other components (not UIs) would pretend to use it. What's about changing it to "9092", so that it also results more similar to the port the LP-CA uses?

let me know.
thanks.

**Comment by imatesiu** [comment]
@gulyx the changes have been applied

**Comment by gulyx** [comment]
thanks @imatesiu ... but i cannot see the updates about the readme. Am I missing anything?

**Comment by imatesiu** [comment]
thanks @gulyx ! now readme has been committed.

**Pull request merged**
