### PR TITLE
Update transformation with last wiki structure

### PR DESCRIPTION
**Pull request by woshilapin**
Here is a first attempt to update the ATL according to the last version of the XWiki structure.  This PR will probably have to be refined before being merged (for example, updating the ASM files?).

### CODE REVIEW

**Comment by woshilapin** [comment]
I've also try to update some of the information about `<parent>` element for wiki pages.

**Comment by woshilapin** [comment]
This PR is probably outdated by #114.

**Comment by gulyx** [comment]
@Bitico, 
could you confirm that this PR has been replaced by #114, and so it can be removed?

**Comment by Bitico** [comment]
@gulyx yes! We can remove this one.

**Comment by gulyx** [comment]
@woshilapin, can you close and remove it?

**Pull request closed without merging**
