### PR TITLE
Add REST API for receiving monitoring events

### PR DESCRIPTION
**Pull request by tomjorquera**
This is a draft proposal for an event monitoring REST API.

Currently, 5 event types are defined: processes start and stop, tasks start and stop, and session score updates.

For each event type, the REST API exposes a dedicated POST method, along with an AbstractEvent implementation.

Some notes:
* I created a new `mon` package, to avoid cluttering `sim`. It seemed relevant, but can be debated...
* My initial plan on having only a single `receiveEvent(AbstractEvent)` method in the API fell flat, as using a hierarchy of classes does not play nice with REST automatic conversions. This design is more simple and idiomatic
* Event with the previous point, I kept the design where events expose an `EventType getType()` method, considering it may prove useful during implementation.
* Currently the API is unidirectional: only the core side exposes methods. I still created a `Bridge` and `BridgeInterface` for consistency, and in case we decide to make the design evolve.

### CODE REVIEW

**Comment by gulyx** [comment]
Tom, I do not think that we should introduce a new component.
I am totally fine with separating "sim" from "mon" in two different packages,
but from the point of view of the CP, they should still appear as a single component.

In other words, partitioning the package "eu.learnpad.simulator" into : "eu.learnpad.simulator.sim"
and "eu.learnpad.simulator.mon" it is fine, but they should work under commons BridgeInterface and
CoreFacade.

**Comment by tomjorquera** [comment]
Just to let you know, I made the modifications to move everything into the sim package.

Also, on a side note, I made some changes keep this PR "fresh" re. PR #109.

**Comment by woshilapin** [comment]
@gulyx, please tell me if this is ok for you to merge this one.  Sounds good to me now.

**Comment by gulyx** [comment]
Sorry @tomjorquera, I do not see the anything that direct refers to the monitoring (e.g. "eu.learnpad.simulator.mon"). This because the modifications only affects the API specification
of the simulator, right?

Also, I am a bit doubtful about the placement of the package "eu.learnpad.sim.rest.event.impl" inside the lp-cp-apis bundle? But probably I am wrong, and that is the right place where we should put the concrete definition of the events both CP and SIM can deal with ...

Let me know.

**Comment by tomjorquera** [comment]
@gulyx, I do not think really required to separate these in a `mon` sub-package, since the API concerns the Core Platform side (and will be used by the monitoring, but in the absolute could be used by other components). I think that we should introduce a `mon` sub-package if we decide the define an API to be implemented on the monitoring side.
Of course that's just my PoV, if you feel it is better to separate things more explicitly, I can do it with minimal effort.

Regarding the `eu.learnpad.sim.rest.event.impl`, the naming convention is a bit unfortunate in this case (to my defence it is quite standard in Java :sweat_smile: ). I will try to change it to a more appropriate name.
I think its content should be kept here in any case, as it defines the structure of the JSON objects exchanged via the REST API, and so is a part of the REST specification.

**Comment by gulyx** [comment]
@tomjorquera 

> @gulyx, I do not think really required to separate these ... ... 
> ... ... 
> ... I can do it with minimal effort.

Ok fine with me.

> Regarding the eu.learnpad.sim.rest.event.impl, ... 
> ... ...
> ... REST specification.

OK also for this point. 
About the set of considered events, I believe it is fine,
but n case @acalabro may need to modify/add
some event, he could contribute and change them also later.

@woshilapin, I would say that we can merge it for the moment.

**Comment by acalabro** [comment]
Ok for me.
As you said @gulyx ,the structure of the event and the Enum allow us to extend it if needed.
At the actual stage, we should notify out of the sim(mon) only the events already defined.

**Pull request merged**
