### PR TITLE
Added lola to the build of the verification

### LINKED ISSUE #388: [mv][testbed] Executing Lola
@damianofalcioni, @imatesiu, @woshilapin, @semmeneg, @tomjorquera @acalabro 
- lola is the analyzer "generated" and executed by the MV component 
- lola will always be located in /tmp
- the current version of lola is classified as follows  (by the 'file' command):
  `lola: ELF 32-bit LSB  executable, Intel 80386, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=894bb774ae645f80b983900e304432bf7ebf2087, not stripped`

in conclusion the server hosting Learn PAd must have the 32-bit compatibility libraries installed.

not sure the http://testbed.learnpad.eu currently has this libraries installed.

### PR DESCRIPTION
**Pull request by cjdelisle**
This should finally close #388

### CODE REVIEW

**Comment by gulyx** [comment]
sorry @cjdelisle @yflory what this commit https://github.com/LearnPAd/learnpad/pull/601/commits/753a0c016ee92dbdce6d3e2a26fd1078feaa675b is about?
I understood this PR focuses on the integration of lola ....

please let me know.

**Comment by cjdelisle** [comment]
We have included some additional code on top of this PR which displays information about the recommendations. Putting it in a different branch would possibly be problematic because this is only tested on top of "that".

**Comment by gulyx** [comment]
@cjdelisle possibly i would like to avoid this lola integration before the review ... can you provide the contribution of commits https://github.com/LearnPAd/learnpad/pull/601/commits/e7fbf630cf1fbdda0b28e30b81c36c9ba5484fe4 and https://github.com/LearnPAd/learnpad/pull/601/commits/753a0c016ee92dbdce6d3e2a26fd1078feaa675b in a separate PR?

**Comment by gulyx** [comment]
@cjdelisle thanks for you support/help and ...

**Pull request merged**
