### PR TITLE
Or patch for unsupported operation exception in cbr adapter

### PR DESCRIPTION
**Pull request by gulyx**
... and also added a dependency to the OR pom.
Details are available here : https://github.com/LearnPAd/learnpad/issues/342

---
This change is [Reviewable](https://reviewable.io/reviews/learnpad/learnpad/348)

### CODE REVIEW

**Comment by gulyx** [comment]
@tomjorquera @woshilapin I guess the PR #348 cannot be accepted yet.
The contributions i made are fine (maybe i would add some further refinement) but i discovered
a bug that appears to be related to the marshalling and unmarshaling of the object Recommendations that are generated inside the OR. Specifically this bug should only concerns those Recommendations which involve cases.

In particular i am thinking that the specification of the map as Map<String, Object> inside the class SimilarCase (see : https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/SimilarCase.java#L24 ) is fine with Java but it could be not with JAXB. In fact, in the OR code the "Object" in the map may result instantiated as "ArrayList" :

https://github.com/LearnPAd/learnpad/blob/master/lp-ontology-recommender/src/main/java/eu/learnpad/ontology/recommender/cbr/CBRAdapter.java#L152

which looks "too similar" with the error message JAXB notifies in the exception during the marshalling and unmarshaling.

What do you (i.e. @semmeneg @tomjorquera @woshilapin ) think about it?

If this is confirmed, how to proceed? We may close decide to finalize and #348, and then open another 
PR setting the map in  SimilarCase to Map<String, List<String>> or something similar.

**Comment by gulyx** [comment]
See https://github.com/LearnPAd/learnpad/issues/342#issuecomment-201557777

**Comment by gulyx** [comment]
@semmeneg, @tomjorquera , @woshilapin please consider the commit i just released. This should somehow fix the problem we had marshaling and marshaling recommendations with JAXB, and consequently the integration between the OR and SIM ( + CP and CW ). 

Note that this PR limits the data-types that can be stored/referenced within a SimilarCase (see https://github.com/LearnPAd/learnpad/pull/348/commits/e57af4a3ef3c50af46706e7be54b1ab0c273d089 ). I believe this is not a major problem (at least for the moment), but please let me know. We may also think to apply similar restrictions to https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/SimulationData.java#L34 and to https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/SimulationData.java#L36

@semmeneg since I introduced significant changes into the OR code, please help me in understanding if these modifications have side effects over other parts of the code ... for the best i understood with my tests the scope of the modification in currently limited, but please double check. @tomjorquera @woshilapin wait for @semmeneg's answer before accepting the PR.

**Comment by semmeneg** [comment]
The changes are ok for me. No side effects expected up to now. As you 
said, in the next release we might adapt the similar cases response if 
required. But for now it's fine.

**Pull request merged**
